name: KMP library compilation check

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache ~/.m2/repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('buildSrc/src/main/kotlin/**/*') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Cache ~/.konan
        uses: actions/cache@v1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-kn-${{ hashFiles('buildSrc/build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-kn
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Check plugin
        run: ./gradlew -PpluginPublish publishPluginPublicationToMavenLocal
      - name: Check core
        run: ./gradlew -PcorePublish :widgets:publishToMavenLocal
      - name: Cocoapods install
        run: (cd sample/ios-app && pod install)
      - name: Check additions
        run: |
          ./gradlew -PadditionsPublish \
          :widgets-flat:publishToMavenLocal \
          :widgets-bottomsheet:publishToMavenLocal \
          :widgets-sms:publishToMavenLocal \
          :widgets-datetime-picker:publishToMavenLocal \
          :widgets-collection:publishToMavenLocal \
          :widgets-image-network:publishToMavenLocal