name: KMP library compilation check

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check plugin
        run: ./gradlew -PpluginPublish publishPluginPublicationToMavenLocal
      - name: Check core
        run: ./gradlew -PcorePublish :widgets:publishToMavenLocal
      - name: Cocoapods install
        run: (cd sample/ios-app && pod install)
      - name: Check flat
        run: ./gradlew -PadditionsPublish :widgets-flat:publishToMavenLocal 
      - name: Check bottomsheet
        run: ./gradlew -PadditionsPublish :widgets-bottomsheet:publishToMavenLocal 
      - name: Check sms
        run: ./gradlew -PadditionsPublish :widgets-sms:publishToMavenLocal 
      - name: Check datetime-picker
        run: ./gradlew -PadditionsPublish :widgets-datetime-picker:publishToMavenLocal 
      - name: Check collection
        run: ./gradlew -PadditionsPublish :widgets-collection:publishToMavenLocal 
