name: KMP library publish

on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        name: Set up JDK 1.8
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        name: Cache ~/.m2/repository
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('buildSrc/src/main/kotlin/**/*') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/cache@v1
        name: Cache ~/.konan
        with:
          path: ~/.konan
          key: ${{ runner.os }}-kn-${{ hashFiles('buildSrc/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-kn-
      - name: Publish plugin
        run: ./gradlew -PdevPublish -PpluginPublish publishPluginPublicationToBintrayDevRepository -DBINTRAY_USER=${{ secrets.BINTRAY_USER }} -DBINTRAY_KEY=${{ secrets.BINTRAY_KEY }}
      - name: Publish core
        run: ./gradlew -PdevPublish -PcorePublish :widgets:publishAllPublicationsToBintrayDevRepository -DBINTRAY_USER=${{ secrets.BINTRAY_USER }} -DBINTRAY_KEY=${{ secrets.BINTRAY_KEY }}
      - name: Cocoapods install
        run: (cd sample/ios-app && pod install)
      - name: Publish additions
        run: |
          ./gradlew -PdevPublish -PadditionsPublish \
          :widgets-flat:publishAllPublicationsToBintrayDevRepository \
          :widgets-bottomsheet:publishAllPublicationsToBintrayDevRepository \
          :widgets-sms:publishAllPublicationsToBintrayDevRepository \
          :widgets-datetime-picker:publishAllPublicationsToBintrayDevRepository \
          :widgets-collection:publishAllPublicationsToBintrayDevRepository \
          :widgets-image-network:publishAllPublicationsToBintrayDevRepository \
          -DBINTRAY_USER=${{ secrets.BINTRAY_USER }} -DBINTRAY_KEY=${{ secrets.BINTRAY_KEY }}
