name: KMP library publish dev version

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache ~/.m2/repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('buildSrc/src/main/kotlin/**/*') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Cache ~/.konan
        uses: actions/cache@v1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-kn-${{ hashFiles('buildSrc/build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-kn
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Compile plugin
        run: ./gradlew -PdevPublish -PpluginPublish publishPluginPublicationToMavenLocal
      - name: Compile core
        run: ./gradlew -PdevPublish -PcorePublish :widgets:publishToMavenLocal
      - name: Cocoapods install
        run: (cd sample/ios-app && pod install)
      - name: Compile additions
        run: |
          ./gradlew -PdevPublish -PadditionsPublish \
          :widgets-flat:build \
          :widgets-bottomsheet:build \
          :widgets-sms:build \
          :widgets-datetime-picker:build \
          :widgets-collection:build \
          :widgets-image-network:build \
          :widgets-permissions:build \
          :widgets-media:build
      - name: Publish all to bintray
        run: |
          ./gradlew --no-parallel -PdevPublish \
          -Dorg.gradle.internal.publish.checksums.insecure=true \
          publishPluginPublicationToBintrayDevRepository \
          :widgets:publishAllPublicationsToBintrayDevRepository \
          :widgets-flat:publishAllPublicationsToBintrayDevRepository \
          :widgets-bottomsheet:publishAllPublicationsToBintrayDevRepository \
          :widgets-sms:publishAllPublicationsToBintrayDevRepository \
          :widgets-datetime-picker:publishAllPublicationsToBintrayDevRepository \
          :widgets-collection:publishAllPublicationsToBintrayDevRepository \
          :widgets-image-network:publishAllPublicationsToBintrayDevRepository \
          :widgets-permissions:publishAllPublicationsToBintrayRepository \
          :widgets-media:publishAllPublicationsToBintrayRepository \
          -DBINTRAY_USER=${{ secrets.BINTRAY_USER }} -DBINTRAY_KEY=${{ secrets.BINTRAY_KEY }} \
          --stacktrace
